[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist/functions"

[dev]
  command = "npm run dev"
  port = 8888
  publish = "dist"
  functions = "dist/functions"
  targetPort = 5176
  framework = "#auto"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200